### ISSUE TITLE
Showcase not displaying `shared/box` correctly?

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#145]
See http://localhost:3000/docs/showcase/previews/partials/box for an example.

<img width="1362" alt="Screenshot 2023-03-01 at 4 58 20 PM" src="https://user-images.githubusercontent.com/217218/222311000-f9d5dfa7-9bc4-4191-9bc4-08ebc1e26bdd.png">

**Comment by andrewculver** [comment]
Should look more like this:

<img width="1199" alt="Screenshot 2023-03-01 at 5 58 48 PM" src="https://user-images.githubusercontent.com/217218/222311203-3586b4c7-c31b-4d14-9171-623e6a3c450f.png">

**Comment by kaspth** [comment]
Looks like it's something to do with dark mode, if I remove `dark:bg-opacity-50` from here https://github.com/bullet-train-co/bullet_train-core/blob/d848f7cdd7b55be4efbc6169df1b7af470da9eae/bullet_train-themes-light/app/views/themes/light/_box.html.erb#L11

The box starts looking like this:

<img width="1068" alt="Screenshot 2023-03-02 at 04 01 14" src="https://user-images.githubusercontent.com/350807/222320025-6df66ebb-2f57-42cd-b86f-bba494e68757.png">

It looks like it was introduced in the recent Tailwind PR #106 here https://github.com/bullet-train-co/bullet_train-core/pull/106/files#diff-6cfef8a94497a8cb9d388709a83f7f88f02794c88ab0c4efa02b2a497421a01dR11

I don't understand the purpose of the opacity setting, is it intentional? If it is, then we'll need some changes, but I don't know what.

**Comment by kaspth** [comment]
Fixed by shipping a dark mode for Showcase in https://github.com/bullet-train-co/showcase/pull/42

So now the contrasts are easier to spot:

<img width="765" alt="Screenshot 2023-03-05 at 04 08 43" src="https://user-images.githubusercontent.com/350807/222939576-eb697aa4-c87e-40b3-9348-b5817edfe9a8.png">
