### ISSUE TITLE
Checkbox not picking up primary color.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#218]
When `config/initializers/theme.rb` is:

```
BulletTrain::Themes::Light.color = :pink
BulletTrain::Themes::Light.secondary_color = :violet
```

The result is:

<img width="503" alt="Screen Shot 2023-03-24 at 1 06 33 PM" src="https://user-images.githubusercontent.com/217218/227628449-871a8d61-a6a2-4c29-832a-33175fde380f.png">

**Comment by gazayas** [comment]
Currently stuck on this one, I'll post some information I found.

Checkboxes should be styled with `accent-{color}` according to [the docs](https://tailwindcss.com/docs/accent-color#setting-the-accent-color).
However, since we use the `@tailwindcss/forms` plugin, it causes some issues.
[comment from related issue](https://github.com/tailwindlabs/tailwindcss/issues/6367#issuecomment-991120086):
> The accent-color sets the actual accent-color property. However, when you are using the @tailwindcss/forms plugin, then we remove the default appearance and replace it with a styleable checkbox with a custom svg.
If you want to use the same accent color, then you can use the text color classes instead: https://play.tailwindcss.com/oigBo8s03D
The code example contains this example: https://github.com/tailwindlabs/tailwindcss-forms#basic-usage

However, replacing `text-blue` in the checkbox class doesn't change the color:
```ruby
"text-#{BulletTrain::Themes::Light.color}"
```

**Comment by andrewculver** [comment]
@gazayas If you try just `text-primary`, does that fix it?

**Comment by gazayas** [comment]
@andrewculver No luck 😕 the closest I get is a pink focus ring, but only in Firefox on dark mode:

![Screenshot from 2023-03-26 07-41-40](https://user-images.githubusercontent.com/10546292/227745780-52a93022-9b60-4b88-afd3-7eedaa4a0d99.png)

Granted, the following worked for the checkbox (taken from a comment in the same issue [here](https://github.com/tailwindlabs/tailwindcss/issues/6367#issuecomment-991120086)), but it took away a lot of our for styles, so I figured this wasn't the answer:
(in the Tailwind config file)
```js
plugins: [
 require("@tailwindcss/forms")({
   strategy: 'class',
 }),
],
```

**Comment by jagthedrummer** [comment]
I just figured this one out. It seems that `text-red` isn't sufficient for the forms plugin. You have to do `text-red-500`, or some other number to tell it which shade to use.

I got things to work in https://github.com/bullet-train-co/bullet_train-core/pull/567 by using `text-primary-500`.

**Comment by gazayas** [comment]
Awesome, glad this one got sorted out! We also were tweaking a lot with Tailwind at the time, so I wonder if something changed over time.
