### ISSUE TITLE
Unexpected data in example JSON responses on Redocly.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#226]
Seeing a bunch of attributes from `Scaffolding::CompletelyConcrete::TangibleThing` in [the response examples for `Webhooks::Outgoing::Endpoint` and `Webhooks::Outgoing::Event`](https://orange-impala-9.redoc.ly/#tag/Webhooks::Outgoing::Endpoint).

**Comment by newstler** [comment]
This is happening because of `scaffolding_completely_concrete_tangible_thing` variable name not being transformed to the current model name in [bullet_train-api/app/views/api/v1/open_api/shared/_paths.yaml](https://github.com/bullet-train-co/bullet_train-core/blob/74d80062e06477d92f40b6c0376f5f42d30d0659/bullet_train-api/app/views/api/v1/open_api/shared/_paths.yaml.erb) by [bullet_train-super_scaffolding/lib/scaffolding/class_names_transformer.rb](https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-super_scaffolding/lib/scaffolding/class_names_transformer.rb). Lines to be transformed:

- [34](https://github.com/bullet-train-co/bullet_train-core/blob/74d80062e06477d92f40b6c0376f5f42d30d0659/bullet_train-api/app/views/api/v1/open_api/shared/_paths.yaml.erb#L34)
- [60](https://github.com/bullet-train-co/bullet_train-core/blob/74d80062e06477d92f40b6c0376f5f42d30d0659/bullet_train-api/app/views/api/v1/open_api/shared/_paths.yaml.erb#L60)
- [71](https://github.com/bullet-train-co/bullet_train-core/blob/74d80062e06477d92f40b6c0376f5f42d30d0659/bullet_train-api/app/views/api/v1/open_api/shared/_paths.yaml.erb#L71)
- [94](https://github.com/bullet-train-co/bullet_train-core/blob/74d80062e06477d92f40b6c0376f5f42d30d0659/bullet_train-api/app/views/api/v1/open_api/shared/_paths.yaml.erb#L94)
- [116](https://github.com/bullet-train-co/bullet_train-core/blob/74d80062e06477d92f40b6c0376f5f42d30d0659/bullet_train-api/app/views/api/v1/open_api/shared/_paths.yaml.erb#L116)
- [127](https://github.com/bullet-train-co/bullet_train-core/blob/74d80062e06477d92f40b6c0376f5f42d30d0659/bullet_train-api/app/views/api/v1/open_api/shared/_paths.yaml.erb#L127)
