### ISSUE TITLE
Adding Validations to `User` can break `Platform::Application`

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train-core#271]
When adding a presence validator on User for first and last name, Platform::Application tests begin failing.

Apparently when creating a Platform::Application an after_create hook executes... https://github.com/bullet-train-co/bullet_train-core/blob/a2d51701973c45c16aedcc1edab82c7a9ea95c46/bullet_train-api/app/models/platform/application.rb#L34-L39

This hook creates a user but fails if the created User (and probably the associated Membership) are invalid according to any new validations.

I don't think that system-level stuff like this should depend on domain models of the application.

**I think the more general problem here is that adding any new validations to User may cause the User created for the Platform::Application to fail.**

Edit: Changed the issue title because it's not really about names

**Comment by newstler** [comment]
Probably it's not connected to this particular issue, but it's quite a bad practice to have user's first and last names separated: in different countries and cultures there may be only one, or many words representing the name. So usually the good practice is to request filling "Full name" in one text field. More [here](https://www.w3.org/International/questions/qa-personal-names). @andrewculver

**Comment by olbrich** [comment]
@newstler Yeah, fully aware of that. There are business reasons for separating them.

**Comment by gazayas** [comment]
It seems like a lot more than just `Platform::Application` tests break when adding validations for first and last name. The factories provide names for onboarded users, but not for the regular `:user` factory, so I feel like at this point it's more of developer preference which they'd have to code into the tests as well rather than just something we need to change in `bullet_train-core`.

With that being said, I like the idea of having one name field, and although it would take some work for both us and the developers upgrading to a would-be new version of Bullet Train, I'm down with it if it's better practice.

> I don't think that system-level stuff like this should depend on domain models of the application.

Agreed.

Not sure if it's currently worth patching a "fix" right now if in the long run we should be changing the schema itself, which I personally think would be the next step we want to take.

**Comment by olbrich** [comment]
In my case, I just updated the factories so that a new user always has the appropriate names initialized, which seems like a pretty reasonable thing to do if you add new validations. 

**I think the more general problem here is that adding any new validations to `User` may cause the `User` created for the `Platform::Application` to fail.**

On the subject of names... I personally think it would be better to err on the side of a more complex name system instead of just making a single name field. There are lots of use cases for things like sorting that may need to understand the name structure to work and there's no reliable way to do that if all the name information is lumped together in a single field.

**Comment by gazayas** [comment]
Posting here for more context: https://discord.com/channels/836637622432170028/1102699736810663937/1102700360902135968

**Comment by jagthedrummer** [comment]
Only tangentially related, but it's always seemed weird to me that creating a platform application automatically creates a user that doesn't really seem to _do_ anything. It would be nice if that weren't the case.

**Comment by jagthedrummer** [comment]
Based on discussion here and in the linked Discord thread I'm not sure there's really anything to be done here. I'm going to close this for now. Feel free to reopen it if there's something we can identify that we should fix.
