### ISSUE TITLE
Add a scaffolding system test for new incoming webhooks endpoints.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#453]
Similar to the tests we've got for other Super Scaffolding commands, we should test end-to-end that when someone runs `bin/super-scaffold incoming-webhooks` the resulting controller and model work as expected including being able to receive a webhook.

**Comment by gazayas** [comment]
A couple of mental notes while I work on this.

1. The tunneling docs need to be updated since the `--subdomain` flag for the ngrok CLI tool is deprecated.
2. The help text after super scaffolding pluralizes the provider name when it should just appear as is. The last line in the following, for example, should have `foo_webhooks` as opposed to `foos_webhooks` to work:
```
> bin/super-scaffold crud incoming-webhooks Foo

Writing './app/models/webhooks/incoming/foo_webhook.rb'.
Fixing Standard Ruby on './app/models/webhooks/incoming/foo_webhook.rb'.
Writing './app/controllers/webhooks/incoming/foo_webhooks_controller.rb'.
Fixing Standard Ruby on './app/controllers/webhooks/incoming/foo_webhooks_controller.rb'.
Updating './app/models/webhooks/incoming/foo_webhook.rb'.
Updating 'config/routes.rb'.

1. To receive webhooks in your development environment, you'll need to configure a tunnel.
     See http://bullettrain.co/docs/tunneling for more information.

2. Once you have a tunnel running, you can configure the provider to deliver webhooks to:
     https://your-tunnel.ngrok.io/webhooks/incoming/foos_webhooks
```

https://github.com/bullet-train-co/bullet_train-core/blob/6f67c72da41f78c64e985c930ec8aca08c66347d/bullet_train-incoming_webhooks/lib/bullet_train/incoming_webhooks/scaffolders/incoming_webhooks_scaffolder.rb#L33

**Comment by gazayas** [comment]
Struggling a bit with this one in actually trying to trigger webhook through the ngrok tunnel in the tests. Capybara has `Capybara.app_host`, but tinkering with that or anything similar doesn't seem to do the trick.

I propose creating a controller unit test as opposed to a system test. We would still use the `test/bin` setup file to super scaffold the webhook logic, but I think a controller test will be enough because we can:
1. Verify the newly scaffolded endpoint works
2. Verify the JSON response returns a status of "OK".

Here's what the test would look like:

```ruby
require "test_helper"

class Webhooks::Incoming::ProviderWebhooksTest < ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers

  def setup
    super
    @user = FactoryBot.create(:onboarded_user)
    sign_in @user
    @team = @user.current_team
  end

  test "should get incoming webhook" do
    creative_concept = Scaffolding::AbsolutelyAbstract::CreativeConcept.create(name: "Test Concept")

    webhook_params = {
        data: {
            data: {
              id: 2,
              name: "Test",
              team_id: 1,
              created_at: creative_concept.created_at,
              updated_at: creative_concept.updated_at,
              description: ""
            },
            event_id: "82b4bcd5572b4bcfb5c56c578265cad6",
            event_type: "scaffolding/absolutely_abstract/creative_concept.created",
            subject_id: 2,
            subject_type: "Scaffolding::AbsolutelyAbstract::CreativeConcept"
        },
        processed_at: nil,
        verified_at: nil,
      }
    
    post "/webhooks/incoming/provider_webhooks", params: webhook_params.to_json
    assert_equal response.parsed_body, {"status"=>"OK"}
  end
end
```

The only thing I'm thinking through right now is where to place it. I want it to be in `test/system/super_scaffolding_test.rb` so we don't have to add anymore commands to the CircleCI config, but if we take this route we might have to put it somewhere else in the test directory.

**Comment by jagthedrummer** [comment]
> Struggling a bit with this one in actually trying to trigger webhook through the ngrok tunnel in the tests.

I don't think we need to test it through the tunnel, there's really no guarantee that the tunnel would be open while tests are running.

I think a controller test is fine. System tests are generally for testing user flows that you can drive through a browser. For this type there's not really a flow, it's just making sure that a controller can accept some params and do the right thing with them as a one-off.

**Comment by gazayas** [comment]
Got it, will try to implement the controller test.

**Comment by gazayas** [comment]
Another note to self as I'm working on this one.

It looks like routes aren't properly scaffolded for namespaced incoming webhooks:
`bin/scaffold incoming-webhooks Scaffolding::CompletelyConcrete::TangibleThing`

**Comment by jagthedrummer** [comment]
Reopening this issue because it was partially addressed in https://github.com/bullet-train-co/bullet_train-core/pull/502, but there's still more that we want to do.

In #502 we added a test that is generated for people when the super scaffold an incoming webhook. That give the downstream developer confidence that _their_ code (which we generated for them, but they now own) isn't going to break.

But in addition we should add some tests to ensure that _our_ code around generating the handler and test for the webhook isn't broken.

We need to add a block to `test/bin/setup-super-scaffolding-system-test` that does something like:

```
bin/super-scaffold incoming-webhooks SomeProvider
```

And then add some tests in `test/system/super_scaffolding_test.rb` that checks if we can run the test that we auto-generate. Or maybe we don't need to modify `test/system/super_scaffolding_test.rb` but to just add a step in the super-scaffolding CI job to explicitly run

```
rails test \
  test/controllers/webhooks/incoming/some_provider_webhooks_controller_test.rb \
  test/models/webhooks/incoming/some_provider_webhook_test.rb
```

**Comment by gazayas** [comment]
I like the idea of having this as part of the CI job, and that had come to mind before. That way we won't have to worry about forcing this into a system test of some sort, but still having automation so we don't have to "think" about it. Will see what I can come up with.
