### ISSUE TITLE
Support not rendering `days_ago` attributes when the value is blank.

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train-core#560]
Most partials for attributes in themes simply do not render anything when the value for that attribute is blank.  The `date`, and `date_and_time` attributes have a default_message that can be set to "" to avoid rendering anything.

For consistency, it would be helpful to support this same behavior for the `days_ago` attribute.  

(Also note that this particular attribute is also inconsistent in that it does not use the `public_send` method).

**Comment by jagthedrummer** [comment]
@olbrich, are you saying that instead of seeing "Never" you'd like to see nothing?

If that's the case have you tried setting a blank string for the `global.never` translation key?

https://github.com/bullet-train-co/bullet_train-core/blob/73e32e58f2ff0c74e86b6b2b6279fffaad8138ab/bullet_train/config/locales/en/base.yml#L39-L50

It looks like we should be using that to generate the "Never" string for display:

https://github.com/bullet-train-co/bullet_train-core/blob/60efcfd230f0319b0d2d9f6755d60c03aa4538d7/bullet_train-themes/app/views/themes/base/attributes/_days_ago.html.erb#L6-L10
