### ISSUE TITLE
MiniTest::Spec?

### ISSUE THREAD

**Issue by aaricpittman** [bullet-train-co/bullet_train-core#588]
What are your thoughts on using `MiniTest::Spec`? I see it used in a few individual test files.

**Comment by kaspth** [comment]
Which files are you seeing it used in? I can't find examples via GitHub's search, either here or on bullet-train-co/bullet_train.

Rails uses assertion style by default, and Part of Bullet Train's ethos is to not diverge from Rails' defaults unless there's significant advantage to do so. I personally prefer assertion style, so I'm not too keen on using both spec and assertion style in the codebase. But I'm curious to see the examples. Though I'd also advocate for swapping the spec style files over to assertion style.

If there's anything broken, so that Bullet Train apps can't use `Minitest::Spec` we should fix that.

**Comment by jagthedrummer** [comment]
I generally prefer spec style over assertion style, but I definitely think we should not mix and match. Assertion style is so widely used in the project that I think we should stick with it.

**Comment by aaricpittman** [comment]
@kaspth, are the ones that I saw, https://github.com/search?q=repo%3Abullet-train-co%2Fbullet_train-core+%22minitest%2Fspec%22&type=code.

Personally, I prefer the spec style dsl for writing tests. I think it tends to lead to a more readable test suite, and the context/describe block syntax produces a visual pattern that makes it easy to see what is related. You could probably achieve a similar visual pattern using separate nested test classes.

**Comment by kaspth** [comment]
@aaricpittman I wasn't aware that `Minitest::Spec` still used assertions within the tests! There's definitely something to how the `describe`/`it` blocks read, as long as it doesn't get too nested and complicated.

I do think we should keep them consistent, so I'll look at that.

**Comment by kaspth** [comment]
Ok, I've got a version over here that switches to minitest/test https://github.com/bullet-train-co/bullet_train-core/pull/597

**Comment by andrewculver** [comment]
Yeah, let's use test not spec. Thanks @kaspth!
