### ISSUE TITLE
Showcase previews for Options and Trix Editor are broken

### ISSUE THREAD

**Issue by pascallaliberte** [bullet-train-co/bullet_train-core#870]
This is affecting the published docs at https://bullettrain.co/docs/showcase and are reproducible locally.

Visiting the **Options** showcase preview locally returns:

![CleanShot 2024-06-28 at 13 51 34@2x](https://github.com/bullet-train-co/bullet_train-core/assets/104179/e90b4f4d-10a3-41be-8a9c-85ce34329622)

Visiting the **Trix Editor** showcase preview locally returns:

![CleanShot 2024-06-28 at 13 52 15@2x](https://github.com/bullet-train-co/bullet_train-core/assets/104179/ccf8c8d5-04f3-4d6b-a516-51d35b4bffba)

_Note: the error with the Trix Editor isn't shown if you're logged into the app in localhost._

**Comment by jagthedrummer** [comment]
It looks like this was fixed with #871 & #873. The showcase preview for both Options and Trix Editor are working for me, both when I'm signed in to the demo site and when I'm not.

https://bullettrain.co/docs/showcase/previews/field_partials/options

https://bullettrain.co/docs/showcase/previews/field_partials/trix_editor
